package api.routes.pipelines;

import api.routes.components.DUUIComponentController;
import api.routes.processes.DUUIReusableProcessHandler;
import api.http.DUUIRequestHandler;
import api.requests.validation.UserValidator;
import api.storage.AggregationProps;
import api.storage.DUUIMongoDBStorage;
import com.mongodb.client.AggregateIterable;
import com.mongodb.client.model.*;
import com.mongodb.client.result.DeleteResult;
import org.bson.Document;
import org.bson.conversions.Bson;
import org.bson.types.ObjectId;
import org.texttechnologylab.DockerUnifiedUIMAInterface.monitoring.DUUIStatus;
import spark.Request;
import spark.Response;

import java.time.Instant;
import java.util.*;

import static api.requests.validation.UserValidator.authenticate;
import static api.requests.validation.Validator.isNullOrEmpty;
import static api.requests.validation.Validator.missingField;
import static api.storage.DUUIMongoDBStorage.*;

public class DUUIPipelineController {
    private static final Map<String, DUUIReusableProcessHandler> reusablePipelines = new HashMap<>();

    private static final Set<String> UPDATABLE_FIELDS = Set.of(
        "name",
        "description",
        "settings",
        "tags",
        "times_used",
        "last_used",
        "modified_at"
    );

    private static final Set<String> SORTABLE_FIELDS = Set.of(
        "name",
        "description",
        "created_at",
        "modified_at",
        "status",
        "times_used"
    );

    public static Set<String> getUpdatableFields() {
        return UPDATABLE_FIELDS;
    }


    /**
     * Retrieve one pipeline given its id.
     *
     * @param id A unique 24 character identifier generated by MongoDB.
     * @return A document containing the pipeline data or null if nothing matched.
     */
    public static Document getPipelineById(String id) {
        Document result;

        try {
            result =
                DUUIMongoDBStorage
                    .Pipelines()
                    .find(Filters.eq(new ObjectId(id)))
                    .first();

        } catch (IllegalArgumentException exception) {
            result = null;
        }

        if (result == null) return null;

        List<Document> components = DUUIComponentController.getComponentsForPipeline(id);
        convertObjectIdToString(result);
        return result.append("components", components);
    }

    /**
     * Retrieve one or more pipelines from the database given a userID and {@link AggregationProps} to sort
     * and filter the results.
     *
     * @param userID        The userID to identify pipelines belonging to the account.
     * @param props         Props that determine sort, order, limit and skip values.
     * @param getComponents Wether to include components in the pipeline data.
     * @return A Document containing a list of matched pipelines.
     */
    public static Document getPipelinesByUserID(String userID,
                                                AggregationProps props,
                                                boolean getComponents,
                                                boolean getTemplates) {

        List<Bson> aggregation = new ArrayList<>();
        List<Bson> facet = new ArrayList<>();

        if (getTemplates) {
            aggregation.add(Aggregates.match(Filters.in("user_id", userID, null)));
        } else {
            aggregation.add(Aggregates.match(Filters.eq("user_id", userID)));
        }

        aggregation.add(Aggregates.addFields(new Field<>("oid", new Document("$toString", "$_id"))));
        aggregation.add(Aggregates.project(Projections.excludeId()));


        if (!props.getSort().isEmpty() && SORTABLE_FIELDS.contains(props.getSort())) {
            facet.add(Aggregates.sort(
                props.getOrder() == 1
                    ? Sorts.ascending(props.getSort())
                    : Sorts.descending(props.getSort())
            ));
        }

        if (props.getSkip() > 0) facet.add(Aggregates.skip(props.getSkip()));
        if (props.getLimit() > 0) facet.add(Aggregates.limit(props.getLimit()));

        aggregation.add(Aggregates.facet(
            new Facet("pipelines", facet),
            new Facet("count", Aggregates.count())
        ));

        AggregateIterable<Document> documents;

        documents = DUUIMongoDBStorage
            .Pipelines()
            .aggregate(aggregation);


        Document result = documents.into(new ArrayList<>()).get(0);
        List<Document> findings = result.getList("pipelines", Document.class);
        findings.forEach(DUUIMongoDBStorage::convertObjectIdToString);
        int count;
        try {
            count = result.getList("count", Document.class).get(0).getInteger("count");
        } catch (IndexOutOfBoundsException exception) {
            count = 0;
        }

        if (getComponents) {
            for (Document pipeline : findings) {
                List<Document> components = DUUIComponentController
                    .getComponentsForPipeline(pipeline.getString("oid"));

                pipeline.append("components", components);
            }
        }

        return new Document("pipelines", findings).append("count", count);

    }

    public static String insertOne(Request request, Response response) {
        String authorization = request.headers("Authorization");

        Document user = authenticate(authorization);
        if (isNullOrEmpty(user)) return UserValidator.unauthorized(response);

        Document body = Document.parse(request.body());

        String name = body.getString("name");
        if (name.isEmpty()) return missingField(response, "name");

        List<Document> components = body.getList("components", Document.class);
        if (components.isEmpty()) return missingField(response, "components");

        String template = request.queryParamOrDefault("template", "false").toLowerCase();
        List<String> tags = body.getList("tags", String.class);

        Document pipeline = new Document("name", name)
            .append("description", body.getString("description"))
            .append("created_at", Instant.now().toEpochMilli())
            .append("modified_at", Instant.now().toEpochMilli())
            .append("settings", body.get("settings", Document.class))
            .append("times_used", 0)
            .append("last_used", null)
            .append("status"
                , DUUIStatus.INACTIVE)
            .append("tags", tags)
            .append("user_id", template.equals("true") ? null : user.getObjectId("_id").toString());

        DUUIMongoDBStorage
            .Pipelines()
            .insertOne(pipeline);

        convertObjectIdToString(pipeline);
        String id = pipeline.getString("oid");
        components.forEach(c -> {
                c.put("pipeline_id", id);
                c.remove("oid");
                c.remove("id");
                c.put("index", components.indexOf(c));
            }
        );

        DUUIMongoDBStorage
            .Components()
            .insertMany(components);


        Document updatePipeline = getPipelineById(id);
        if (updatePipeline == null) return DUUIRequestHandler.notFound(response);

        response.status(201);
        return updatePipeline.toJson();
    }

    public static void updateOne(String id, Document updates) {
        updates.append("modified_at", Instant.now().toEpochMilli());
        DUUIMongoDBStorage
            .updateDocument(
                DUUIMongoDBStorage.Pipelines(),
                Filters.eq(new ObjectId(id)),
                updates,
                UPDATABLE_FIELDS
            );

        List<Document> components = updates.getList("components", Document.class);
        if (!isNullOrEmpty(components)) {
            for (Document component : components) {
                DUUIComponentController
                    .setIndex(
                        component.getString("oid"),
                        components.indexOf(component));
            }
        }
    }


    public static String startService(Request request, Response response) {
        String pipeline_id = request.params(":id");

        DUUIMongoDBStorage.Pipelines()
            .findOneAndUpdate(
                Filters.eq(new ObjectId(pipeline_id)),
                Updates.set("status", DUUIStatus.SETUP)
            );

        try {
            Document pipeline = getPipelineById(pipeline_id);
            if (pipeline == null) return DUUIRequestHandler.notFound(response);

            DUUIReusableProcessHandler handler = new DUUIReusableProcessHandler(pipeline);
            reusablePipelines.put(pipeline_id, handler);

        } catch (Exception e) {
            response.status(500);
            return e.toString();
        }

        DUUIMongoDBStorage.Pipelines().findOneAndUpdate(
            Filters.eq(new ObjectId(pipeline_id)),
            Updates.set("status", DUUIStatus.IDLE)
        );

        response.status(200);
        return new Document("status", DUUIStatus.IDLE).toJson();
    }

    public static String stopService(Request request, Response response) {
        String pipeline_id = request.params(":id");

        DUUIReusableProcessHandler handler = reusablePipelines.get(pipeline_id);
        if (handler == null) return DUUIRequestHandler.notFound(response);

        DUUIMongoDBStorage.Pipelines().findOneAndUpdate(
            Filters.eq(new ObjectId(pipeline_id)),
            Updates.set("status", DUUIStatus.SHUTDOWN)
        );

        try {
            handler.shutdown();
        } catch (Exception e) {
            response.status(500);
            return e.toString();
        }

        DUUIMongoDBStorage.Pipelines().findOneAndUpdate(
            Filters.eq(new ObjectId(pipeline_id)),
            Updates.set("status", DUUIStatus.INACTIVE)
        );

        response.status(200);
        return new Document("status", DUUIStatus.INACTIVE).toJson();
    }


    public static void setServiceStartTime(String id, long serviceStartTime) {
        DUUIMongoDBStorage
            .getClient()
            .getDatabase("duui")
            .getCollection("pipelines")
            .findOneAndUpdate(
                Filters.eq(new ObjectId(id)),
                Updates.set("serviceStartTime", serviceStartTime)
            );
    }


    public static Map<String, DUUIReusableProcessHandler> getReusableProcesses() {
        return reusablePipelines;
    }

    public static DUUIReusableProcessHandler getReusableProcess(String pipelineId) {
        return reusablePipelines.get(pipelineId);
    }

    public static void removeReusableProcess(String pipelineID) {
        reusablePipelines.remove(pipelineID);
    }

    public static boolean deletePipeline(String pipelineID) {
        DeleteResult result = Pipelines()
            .deleteOne(
                Filters.eq("_id", new ObjectId(pipelineID))
            );

        return result.getDeletedCount() > 0;
    }

    public static void interruptIfRunning(String pipelineID) {
        if (reusablePipelines.containsKey(pipelineID)) {
            reusablePipelines.get(pipelineID).shutdown();
            reusablePipelines.remove(pipelineID);
        }
    }
}
